controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint_left_leg_1
        - joint_left_leg_2  
        - joint_left_leg_3
        - joint_left_leg_4
        - joint_right_leg_1
        - joint_right_leg_2
        - joint_right_leg_3
        - joint_right_leg_4
      state_publish_rate: 50
      action_monitor_rate: 20
      constraints:
        goal_time: 0.6